version: '{build}'
os: Windows Server 2012
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build:
  verbosity: detailed

build_script:
  - mvnw.cmd package -DskipTest

test_script:
  - mvnw.cmd clean install test

branches:
  only:
    - master

cache:
  - C:\Users\appveyor\.maven

matrix:
  fast_finish: true